/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabaniornek2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nurdan
 */
public class gosterme extends javax.swing.JFrame {

    /**
     * Creates new form gosterme
     */
    public gosterme() {
        initComponents();
    }
    
    public Connection  GetConnection()
    {
        Connection con;
        con = null;
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String strDatabase = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ=myDB.mdb;}";
            con = DriverManager.getConnection( strDatabase ,"","");
        }
        catch(Exception e)
        {        
            JOptionPane.showMessageDialog(null, e.toString(), "Student Database", JOptionPane.INFORMATION_MESSAGE);
        }
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("SİL");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Tüm kayıtları göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Yas sınırını giriniz:");

        jButton2.setText("Girilen yaş sınırından büyük olanları göster");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTable1.setComponentPopupMenu(jPopupMenu1);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Connection con = GetConnection();
        try
        {
            if (jTable1.getSelectedRow() != -1)
                {
                Statement stmt;
                String strSQL, ad, yas;
        
                ad = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                //yas = jTextField3.getText();
        
                strSQL ="DELETE FROM KISI where AD='"+ad+"'";
                stmt = con.createStatement();
     
                stmt.execute(strSQL);
                //stmt.close();
        
                Object[][] obj;

                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM KISI");
                rs.next();
                int iCount = rs.getInt("rowcount") ;
                //rs.close() ;

                rs = stmt.executeQuery("SELECT * FROM KISI");              
                
                obj= new Object [iCount][3];

                iCount = 0;

                while ( rs.next() ) 
                {
                    obj[iCount][0] = iCount+1;
                    obj[iCount][1] = rs.getString("AD");
                    obj[iCount][2] = rs.getString("YAS");
                    iCount = iCount+1;
                }
                jTable1.setModel(new javax.swing.table.DefaultTableModel(obj,
                                 new String []{ "S.No:", "AD:", "YAS:" }
            ));
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
      
            Connection con2=  GetConnection();
            Statement stmt= con2.createStatement();
            Object[][] obj;

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM KISI");
            rs.next();
            int iCount = rs.getInt("rowcount") ;
            rs.close() ;

            rs = stmt.executeQuery("SELECT * FROM KISI");

            obj= new Object [iCount][3];

            iCount = 0;

            while ( rs.next() ) 
            {

                obj[iCount][0] = iCount+1;
                obj[iCount][1] = rs.getString("AD");
                obj[iCount][2] = rs.getString("YAS");
                iCount = iCount+1;
            }
            con2.close();

            jTable1.setModel(new javax.swing.table.DefaultTableModel(obj,
                    new String [] {"S.No:", "AD:", "YAS:"}
        ));
        //jTable1.setName("tableStudentInfo"); // NOI18N
        //jScrollPane1.setViewportView(jTable1);
       
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
      
            Connection con2=  GetConnection();
            Statement stmt= con2.createStatement();
            Object[][] obj;

            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS rowcount FROM KISI where YAS>"+jTextField1.getText());
            rs.next();
            int iCount = rs.getInt("rowcount") ;
            rs.close() ;

            rs = stmt.executeQuery("SELECT * FROM KISI where YAS>"+jTextField1.getText());

            obj= new Object [iCount][3];

            iCount = 0;

            while ( rs.next() ) 
            {

                obj[iCount][0] = iCount+1;
                obj[iCount][1] = rs.getString("AD");
                obj[iCount][2] = rs.getString("YAS");
                iCount = iCount+1;
            }
            con2.close();

            jTable1.setModel(new javax.swing.table.DefaultTableModel(obj,
            new String [] { "S.No:", "AD:", "YAS:" }
        ));
        jTable1.setName("tableStudentInfo"); // NOI18N
        //jScrollPane1.setViewportView(jTable1);
       
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gosterme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gosterme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gosterme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gosterme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new gosterme().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
